### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by boryssmejda** [jeremy-rifkin/asserts#3]
Hi, what do you think about adding a CMake support to your library? I could try to prepare it. 
This would help people who use for example Ninja as their build system.
CMake could also help prepare a package from your library, so that other users could easily link to it.
If you would like to further discuss this issue. You can write me an email: borys.smejda@gmail.com

**Comment by jeremy-rifkin** [comment]
Hi @boryssmejda thanks for your interest in the library! CMake support would be good to have, PRs definitely welcome!

**Comment by boryssmejda** [comment]
Hi,
Thank you for your answer 😀 I will definitely try to prepare something
over the weekend. I will let you know once I have something meaningful
ready 😀. Can I add you on LinkedIn? So that the conversation could be
smoother 😅. I know that there is a big time difference since I live in
Europe but still.
Best Regards,
Borys Smejda

pon., 21 lut 2022, 17:45 użytkownik Jeremy Rifkin ***@***.***>
napisał:
