### ISSUE TITLE
MSVC support and fallback to std assert

### ISSUE THREAD

**Issue by OlivierLDff** [jeremy-rifkin/asserts#4]
Hi thanks for the great and interesting work.
Is there any plan to support msvc?
I like the idea of this library to make dev experience better, but I don't want to introduce non cross platform code in my code.
If there is no plan to support msvc, is this library doing any kind of fallback (I didn't see) to the standard `assert` if the platform is not supported by your library?
Have a nice day!

**Comment by jeremy-rifkin** [comment]
Hello, thanks for the interest in the library! I haven't looked at msvc up until now. You make a good point about portability, I'll take a look at what would be needed for msvc support.

**Comment by jeremy-rifkin** [comment]
Pardon the delay here, been working hard on setting up some automated tests for this project! Library should be good to go for MSVC now :)
